package org.specialtripsagency;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class BookingObject extends java.lang.Object implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private org.specialtripsagency.Applicant applicant;

   private String bookingId;

   private org.specialtripsagency.Flight flight;

   public BookingObject()
   {
   }

   public org.specialtripsagency.Applicant getApplicant()
   {
      return this.applicant;
   }

   public void setApplicant(org.specialtripsagency.Applicant applicant)
   {
      this.applicant = applicant;
   }

   public java.lang.String getBookingId()
   {
      return this.bookingId;
   }

   public void setBookingId(java.lang.String bookingId)
   {
      this.bookingId = bookingId;
   }

   public org.specialtripsagency.Flight getFlight()
   {
      return this.flight;
   }

   public void setFlight(org.specialtripsagency.Flight flight)
   {
      this.flight = flight;
   }

   public BookingObject(org.specialtripsagency.Applicant applicant,
         java.lang.String bookingId, org.specialtripsagency.Flight flight)
   {
      this.applicant = applicant;
      this.bookingId = bookingId;
      this.flight = flight;
   }
}
