package org.acme.insurance.policyquote;

import org.acme.insurance.policyquote.Driver;
import org.acme.insurance.policyquote.Policy;
import java.util.Calendar;

rule "NewerVehicleSurcharge"

	no-loop 
	ruleflow-group "surcharge"
	lock-on-active 
    
    when
        //conditions
        $driver : Driver( $id : id)
        $policy : Policy(price > 0, policyType == "CAR", driver == $id, vehicleYear >= Calendar.getInstance().get(Calendar.YEAR) - 3)
    then
        //actions
        modify($policy) {setPrice($policy.getPrice() + 100)};

end
