package org.acme.insurance.policyquote;

import org.acme.insurance.policyquote.Driver;
import org.acme.insurance.policyquote.Policy;

rule "SafeAdults"

    ruleflow-group "calculation"

    when
        $driver : Driver(age > 24, numberOfAccidents < 1, numberOfTickets <= 1, $id : id)
        $policy : Policy(price == 0, policyType == "CAR", driver == $id)
    then
        //actions
        modify($policy) {setPrice(120)};
        
end

