package org.acme.insurance.policyquote;

import org.acme.insurance.policyquote.Driver;
import org.acme.insurance.policyquote.Policy;

rule "SafeYouths"

    ruleflow-group "calculation"

    when
        //conditions
        $driver : Driver(age >= 18 && < 25, numberOfAccidents < 1, numberOfTickets <= 1, $id : id)
        $policy : Policy(price == 0, policyType == "CAR", driver == $id)
    then
        //actions
        modify($policy) {setPrice(450)};
        
end


