package org.specialtripsagency;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BookingObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Booking Id")
	private java.lang.String bookingId;
	@org.kie.api.definition.type.Label(value = "Applicant")
	private org.specialtripsagency.Applicant applicant;
	@org.kie.api.definition.type.Label(value = "Flight")
	private org.specialtripsagency.Flight flight;
	@org.kie.api.definition.type.Label(value = "Hotel")
	private org.specialtripsagency.Hotel hotel;

	public BookingObject() {
	}

	public java.lang.String getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(java.lang.String bookingId) {
		this.bookingId = bookingId;
	}

	public org.specialtripsagency.Applicant getApplicant() {
		return this.applicant;
	}

	public void setApplicant(org.specialtripsagency.Applicant applicant) {
		this.applicant = applicant;
	}

	public org.specialtripsagency.Flight getFlight() {
		return this.flight;
	}

	public void setFlight(org.specialtripsagency.Flight flight) {
		this.flight = flight;
	}

	public org.specialtripsagency.Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(org.specialtripsagency.Hotel hotel) {
		this.hotel = hotel;
	}

	public BookingObject(java.lang.String bookingId,
			org.specialtripsagency.Applicant applicant,
			org.specialtripsagency.Flight flight,
			org.specialtripsagency.Hotel hotel) {
		this.bookingId = bookingId;
		this.applicant = applicant;
		this.flight = flight;
		this.hotel = hotel;
	}

}